<div id="content">


    <div id="page-heading">
        <h1>Edit Role</h1>
    </div>


    <table border="0" width="100%" cellpadding="0" cellspacing="0" id="content-table">
        <tr>
            <th rowspan="3" class="sized"><img src="<?php echo $this->basePath(); ?>/images/shared/side_shadowleft.jpg" width="20" height="300" alt="" /></th>
            <th class="topleft"></th>
            <td id="tbl-border-top">&nbsp;</td>
            <th class="topright"></th>
            <th rowspan="3" class="sized"><img src="<?php echo $this->basePath(); ?>/images/shared/side_shadowright.jpg" width="20" height="300" alt="" /></th>
        </tr>
        <tr>
            <td id="tbl-border-left"></td>
            <td>
                <!--  start content-table-inner ...................................................................... START -->
                <div id="content-table-inner">

                    <!--  start content-table-inner -->
                    <div id="content-table-inner">

                        <table border="0" width="100%" cellpadding="0" cellspacing="0">
                            <tr valign="top">
                                <td>

                                    <div id="msg" class="err"></div>
                                    <!-- start id-form -->
                                    <form action="" method="POST" id="edit_role_form" style="margin-left: 30%;">
                                        <table border="0" cellpadding="0" cellspacing="0"  id="id-form">
                                            <tr>
                                                <th valign="top">Name:</th>
                                                <td><input type="text"  id="name" name="name" value="<?php echo $role->name; ?>" style="width: 200px;" /><span class="err" id="name_err"></span></td>

                                            </tr>

                                            <tr>
                                                <th valign="top"><input type="hidden" value="<?php echo $role->id; ?>" id="id" name="id" /><button class="btn btn-primary" >Edit Role</button></th>
                                                <td> <button class="btn btn-primary" id="admin_cancel" >cancel</button></td>

                                            </tr>



                                        </table>
                                    </form>
                                    <!-- end id-form  -->

                                </td>

                            </tr>

                        </table>

                        <div class="clear"></div>


                    </div>
