<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Internet Dreams</title>

        <?php
        echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/css/screen.css')
                ->prependStylesheet($this->basePath() . '/css/datePicker.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
        ?>

        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.9.1.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-ui.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/date.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.datePicker.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/ajaxupload.3.5.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/global.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/admin.js', 'text/javascript');
        ?>
        <script type="text/javascript">
            function get_base_url() {
                return '<?php echo $this->basePath(); ?>';
            }
        </script>



    </head>
    <body> 
        <!-- Start: page-top-outer -->
        <div id="page-top-outer" style="margin-top: -64px;">    

            <!-- Start: page-top -->
            <div id="page-top">



                <div class="clear"></div>

            </div>
            <!-- End: page-top -->

        </div>
        <!-- End: page-top-outer -->

        <div class="clear">&nbsp;</div>

        <!--  start nav-outer-repeat................................................................................................. START -->
        <div class="nav-outer-repeat"> 
            <!--  start nav-outer -->
            <div class="nav-outer"> 

                <!-- start nav-right -->
                <div id="nav-right">

                    <div class="nav-divider">&nbsp;</div>

                    <a href="<?php echo $this->basePath(); ?>/index.php/administrator/index/logout" id="logout"><img src="<?php echo $this->basePath(); ?>/images/shared/nav/nav_logout.gif" width="64" height="14" alt="" /></a>
                    <div class="clear">&nbsp;</div>



                </div>
                <!-- end nav-right -->


                <!--  start nav -->
                <div class="nav">
                    <div class="table">

                        <ul class="<?php
                        if (isset($admin) && ($admin))
                            echo $admin;
                        else
                            echo 'select'
                            ?>" ><li><a href="<?php echo $this->basePath(); ?>/index.php/administrator/index/index"><b>User's List</b><!--[if IE 7]><!--></a><!--<![endif]-->

                            </li>
                        </ul>

                        <div class="nav-divider">&nbsp;</div>
                        <ul class="<?php
                        if (isset($category) && ($category))
                            echo $category;
                        else
                            echo 'select'
                            ?>" ><li><a href="<?php echo $this->basePath(); ?>/index.php/administrator/role/index"><b>Role</b><!--[if IE 7]><!--></a><!--<![endif]-->

                            </li>
                        </ul>

                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <!--  start nav -->

            </div>
            <div class="clear"></div>
            <!--  start nav-outer -->
        </div>
        <!--  start nav-outer-repeat................................................... END -->

        <div class="clear"></div>
        <!-- start content-outer ........................................................................................................................START -->
        <div id="content-outer">
            <?php echo $this->content; ?>
            <!--  end content -->
            <div class="clear">&nbsp;</div>
        </div>
        <!--  end content-outer........................................................END -->

        <div class="clear">&nbsp;</div>



    </body>
</html>
