<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Administrator</title>
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/css/screen.css');
        ?>

        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.9.1.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/custom_jquery.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.pngFix.pack.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/global.js', 'text/javascript');
        echo $this->headScript()->prependFile($this->basePath() . '/js/admin.js', 'text/javascript');
        ?>
        <script type="text/javascript">
            $(document).ready(function() {
               // $(document).pngFix( );
            });
        </script>
         <script type="text/javascript">
            function get_base_url() {
                return '<?php echo $this->basePath(); ?>';
            }
        </script>
    </head>
    <body id="login-bg"> 

        <!-- Start: login-holder -->
        <div id="login-holder">

            <!-- start logo -->
            <div id="logo-login">
                <h1>Administrator panel</h1>
            </div>
            <!-- end logo -->

            <div class="clear"></div>

            <!--  start loginbox ................................................................................. -->
            <div id="loginbox">

                <!--  start login-inner -->
                <div id="login-inner">
                    <form action="POST" method="<?php echo $this->basePath(); ?>/index.php/administrator/index/index" id="signin" >
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tr>
                                <th>Username</th>
                                <td><input type="text" id="username" name="username" class="login-inp" /></td>
                            </tr>
                            <tr>
                                <th>Password</th>
                                <td><input type="password" value="" id="password" name="password"  onfocus="this.value = ''" class="login-inp" /></td>
                            </tr>
                            <tr>
                                <th></th>
                                <td valign="top"><input type="checkbox" class="checkbox-size" id="login-check" /><label for="login-check">Remember me</label></td>
                            </tr>
                            <tr>
                                <th></th>
                                <td><input type="submit" class="submit-login"  /></td>
                            </tr>
                        </table>
                    </form>
                </div>
                <!--  end login-inner -->
                <div class="clear"></div>

            </div>
            <!--  end loginbox -->

            <!--  start forgotbox ................................................................................... -->
            <div id="forgotbox">
                <div id="forgotbox-text">Please send us your email and we'll reset your password.</div>
                <!--  start forgot-inner -->
                <div id="forgot-inner">
                    <table border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <th>Email address:</th>
                            <td><input type="text" value=""   class="login-inp" /></td>
                        </tr>
                        <tr>
                            <th> </th>
                            <td><input type="button" class="submit-login"  /></td>
                        </tr>
                    </table>
                </div>
                <!--  end forgot-inner -->
                <div class="clear"></div>
                <a href="" class="back-login">Back to login</a>
            </div>
            <!--  end forgotbox -->

        </div>
        <!-- End: login-holder -->
    </body>
</html>